from pathlib import Path
from typing import Optional

Data = list[set[str]]
DATA: Data

class CursorDB:
    data: dict[str, list[str]] = ...
    def __init__(self, data: Data) -> None: ...
    def search_symlinks(self, key: str, find_similar: bool=...) -> Optional[list[str]]: ...
    def rename_file(self, fp: Path) -> Optional[Path]: ...
