from pathlib import Path
from typing import Any, List, Set, TypeVar, Union

LikePath = TypeVar("LikePath", str, Path)

def chdir(directory: LikePath) -> Any: ...
def remove_util(p: LikePath) -> None: ...

class PNGProvider:
    bitmaps_dir: Path
    def __init__(self, bitmaps_dir: LikePath) -> None: ...
    def get(self, key: str) -> Union[List[Path], Path]: ...

def add_missing_xcursors(
    directory: Path, data: List[Set[str]] = ..., rename: bool = ..., force: bool = ...
) -> bool: ...
def timer(func: Any): ...
def debug(func: Any): ...
