from clickgen.db import CursorDB as CursorDB, DATA as DATA
from pathlib import Path
from typing import Any, Union

def chdir(directory: Union[str, Path]) -> Any: ...
def remove_util(p: Union[str, Path]) -> None: ...

class PNGProvider:
    bitmaps_dir: Path
    def __init__(self, bitmaps_dir: Union[str, Path]) -> None: ...
    def get(self, key: str) -> Union[list[Path], Path]: ...

def add_missing_xcursors(directory: Path, data: list=..., rename: bool=..., force: bool=...) -> None: ...
