from pathlib import Path
from typing import Any, List, Set, Union

from clickgen.core import LikePath as LikePath
from clickgen.db import DATA as DATA
from clickgen.db import CursorDB as CursorDB

def chdir(dir: Union[str, Path]) -> Any: ...
def remove_util(p: Union[str, Path]) -> None: ...

class PNGProvider:
    bitmaps_dir: Path
    def __init__(self, bitmaps_dir: LikePath) -> None: ...
    def get(self, key: str) -> Union[List[Path], Path]: ...

def add_missing_xcursors(
    dir: Path, data: List[Set[str]] = ..., rename: bool = ..., force: bool = ...
) -> bool: ...
def timer(func: Any): ...
def debug(func: Any): ...
