#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
from typing import List, Tuple

parser = argparse.ArgumentParser(
    prog="clickgen",
    description="The hustle free cursor building toolbox.",
)
parser.add_argument(
    "-p",
    "--png",
    metavar="PNG",
    dest="png",
    action="store",
    type=str,
    help="The path to .png file. If animated, Try with masking frame-number using symbol '*'. For Example 'wait-*.png'",
)

parser.add_argument(
    "-xhot",
    metavar="X_CORD",
    dest="xhot",
    action="store",
    default=0,
    type=int,
    help="'x' coordinate of cursor hotspot. (default: %(default)s)",
)

parser.add_argument(
    "-yhot",
    metavar="Y_CORD",
    dest="yhot",
    action="store",
    default=0,
    type=int,
    help="'y' coordinate of cursor hotspot. (default: %(default)s)",
)

parser.add_argument(
    "-t",
    "-type",
    choices=("w", "x", "wx"),
    dest="type",
    default="wx",
    help="Cursor type you want to build. 'w':Windows, 'x':XCursor, 'wx': Both. (default: %(default)s)",
)

parser.add_argument(
    "-xs",
    "--xcursor-sizes",
    dest="sizes",
    default=[22, 24, 28, 32],
    type=List[int],
    help="List of pixel-size. XCursor also supports multiple sizes. (default: %(default)s)",
)

parser.add_argument(
    "-ws",
    "--windows-size",
    dest="windows_size",
    default=26,
    type=int,
    help="Single pixel-size for Windows Cursor. (default: %(default)s)",
)

args = parser.parse_args()

print(args)
