#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse

parser = argparse.ArgumentParser(
    prog="clickgen",
    description="The hustle free cursor building toolbox.",
)
parser.add_argument(
    "-p",
    "--png",
    metavar="PNG",
    dest="png",
    type=str,
    help="Path to .png file. If animated, Try to mask frame-number using asterisk( * ). For Example 'wait-*.png'",
)

parser.add_argument(
    "-hot",
    "--hotspot",
    dest="hotspot",
    metavar="cord",
    nargs=2,
    default=(0, 0),
    type=int,
    help="To set 'x' & 'y' coordinates of cursor's hotspot. (default: %(default)s)",
)
parser.add_argument(
    "-t",
    "--type",
    dest="type",
    choices=("windows", "xcursor", "all"),
    default="all",
    help="Set cursor type, Which you want to build. (default: '%(default)s')",
)

parser.add_argument(
    "-xsize",
    "--xcursor-size",
    dest="x_size",
    metavar="size",
    nargs="+",
    default=[22, 24, 28, 32],
    type=int,
    help="List of pixel-size. XCursor also supports multiple sizes. (default: %(default)s)",
)

parser.add_argument(
    "-wsize",
    "--windows-size",
    dest="win_size",
    metavar="size",
    default=24,
    type=int,
    help="Single pixel-size for Windows Cursor. (default: %(default)s)",
)

args = parser.parse_args()

print(args)
