from clickgen.configparser import parse_toml_file as parse_toml_file
from clickgen.packer.windows import pack_win as pack_win
from clickgen.packer.x11 import pack_x11 as pack_x11
from typing import Any, Dict, Generator

def get_kwargs(args) -> Dict[str, Any]: ...
def cwd(path) -> Generator[None, None, None]: ...
def main() -> None: ...
